# Generated by Django 4.2.28 on 2026-02-20 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevtoolRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=150)),
                ('method', models.CharField(max_length=10)),
                ('url', models.TextField()),
                ('headers', models.JSONField(default=dict)),
                ('body', models.TextField(blank=True)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('response', models.TextField(blank=True)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'system_devtool_request',
                'ordering': ['-created_at'],
            },
        ),
    ]
