# Generated by Django 4.2.28 on 2026-02-16 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WfFlow',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('flow_name', models.CharField(max_length=128, unique=True)),
                ('flow_procedures', models.JSONField()),
                ('enabled', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'wf_flow',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WfJob',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('job_name', models.CharField(max_length=128, unique=True)),
                ('flow_name', models.CharField(max_length=128)),
                ('job_type', models.CharField(default='cron', max_length=16)),
                ('cron_expr', models.CharField(blank=True, max_length=128, null=True)),
                ('run_date', models.DateTimeField(blank=True, null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('next_run', models.DateTimeField(blank=True, null=True)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('last_status', models.CharField(blank=True, max_length=16, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'wf_job',
                'ordering': ['job_name'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WfRunHistory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('flow_name', models.CharField(max_length=128)),
                ('status', models.CharField(default='running', max_length=16)),
                ('trigger_by', models.CharField(blank=True, max_length=64, null=True)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('error_msg', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'wf_run_history',
                'ordering': ['-start_time'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WfRunStep',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('step_name', models.CharField(max_length=128)),
                ('step_order', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(default='pending', max_length=16)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('result_data', models.JSONField(blank=True, null=True)),
                ('error_msg', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'wf_run_step',
                'ordering': ['step_order'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WfVersion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('flow', 'Workflow'), ('module', 'Module')], max_length=16)),
                ('target_name', models.CharField(max_length=192)),
                ('version', models.PositiveIntegerField()),
                ('content', models.TextField()),
                ('changed_by', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'wf_version',
                'ordering': ['-version'],
                'unique_together': {('type', 'target_name', 'version')},
            },
        ),
    ]
