# Generated by Django 5.2 on 2026-02-19 11:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("workflows", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="WfJob",
        ),
    ]
