# Generated by Django 4.2.28 on 2026-02-13 13:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('users', models.ManyToManyField(blank=True, db_table='wf_user_role', related_name='wf_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'wf_role',
                'ordering': ['name'],
            },
        ),
    ]
