# Generated by Django 4.2.28 on 2026-02-25 01:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def seed_user_profiles(apps, schema_editor):
    """Seed UserProfile for all existing users with password_changed_at = now()."""
    User = apps.get_model('auth', 'User')
    UserProfile = apps.get_model('accounts', 'UserProfile')
    from django.utils import timezone as dj_tz
    now = dj_tz.now()
    for user in User.objects.all():
        UserProfile.objects.get_or_create(user=user, defaults={'password_changed_at': now})


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_grouppermission_permission_role_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password_changed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wf_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'wf_user_profile',
            },
        ),
        migrations.RunPython(seed_user_profiles, migrations.RunPython.noop),
    ]
